apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: attendance-service
  name: attendance-service
spec:
  ports:
    - name: "8004"
      port: 8004
      targetPort: 8004
  selector:
    io.kompose.service: attendance-service
