apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: classes-service
  name: classes-service
spec:
  ports:
    - name: "8007"
      port: 8007
      targetPort: 8007
  selector:
    io.kompose.service: classes-service
