apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: grades-service
  name: grades-service
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8002
  selector:
    io.kompose.service: grades-service
