apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: messages-service
  name: messages-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: messages-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: messages-service
    spec:
      containers:
        name: messages-service
        image: mkalejta/messages-service:latest
        env:
          - name: KEYCLOAK_INTERNAL_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_INTERNAL_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_REALM
          - name: MONGO_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_DB_NAME
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_URI
          - name: NODE_PATH
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: NODE_PATH
          - name: PORT_MESSAGES_SERVICE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PORT_MESSAGES_SERVICE
          - name: POSTGRES_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URI
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        ports:
          - containerPort: 8006
            protocol: TCP
      restartPolicy: Always
