apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: messages-service
  name: messages-service
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    io.kompose.service: messages-service
