apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: subjects-service
  name: subjects-service
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: subjects-service
