apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: subjects-service
  name: subjects-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subjects-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: subjects-service
    spec:
      containers:
        - env:
          - name: KEYCLOAK_INTERNAL_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_INTERNAL_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_REALM
          - name: MONGO_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_DB_NAME
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_URI
          - name: NODE_PATH
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: NODE_PATH
          - name: PORT_SUBJECTS_SERVICE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PORT_SUBJECTS_SERVICE
          - name: POSTGRES_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URI
          image: mkalejta/subjects-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          name: subjects-service
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
