apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: timetable-service
  name: timetable-service
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8005
  selector:
    io.kompose.service: timetable-service
