apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: timetable-service
  name: timetable-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: timetable-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: timetable-service
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:latest
          command: ['sh', '-c', 'until curl -sf http://keycloak:8080/realms/gradebook; do echo waiting for keycloak; sleep 5; done']
      containers:
        - name: timetable-service
          image: mkalejta/timetable-service:latest
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: KEYCLOAK_INTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_INTERNAL_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_REALM
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB_NAME
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: NODE_PATH
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_PATH
            - name: PORT_TIMETABLE_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_TIMETABLE_SERVICE
            - name: POSTGRES_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_URI
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          ports:
            - containerPort: 8005
              protocol: TCP
      restartPolicy: Always
