apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: users-service
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: users-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: users-service
    spec:
      containers:
        - env:
          - name: ADMIN_KEYCLOAK_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: ADMIN_KEYCLOAK_CLIENT_ID
          - name: ADMIN_KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ADMIN_KEYCLOAK_CLIENT_SECRET
          - name: KEYCLOAK_INTERNAL_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_INTERNAL_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: KEYCLOAK_REALM
          - name: MONGO_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_DB_NAME
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: MONGO_URI
          - name: NODE_PATH
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: NODE_PATH
          - name: PORT_USERS_SERVICE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: PORT_USERS_SERVICE
          - name: POSTGRES_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: POSTGRES_URI
          image: mkalejta/users-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          name: users-service
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - name: users-csv
              mountPath: /usr/src/app/csv/created-users.csv
      restartPolicy: Always
      volumes:
        - name: users-csv
          hostPath:
            path: /run/desktop/mnt/host/c/Users/kalej/Uczelnia/DziennikElektroniczny/services/users-service/created-users.csv
            type: FileOrCreate
