version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - gradebook-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - keycloak_postgres
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - gradebook-net
    restart: unless-stopped

  keycloak_postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - gradebook-net
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT:-8081}:8081"
    environment:
      - KEYCLOAK_PUBLIC_URL=${KEYCLOAK_PUBLIC_URL}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      - keycloak
    networks:
      - gradebook-net
    restart: unless-stopped

  users-service:
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "${USERS_SERVICE_PORT:-8001}:8001"
    environment:
      PORT_USER_SERVICE: ${USERS_SERVICE_PORT:-8001}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  grades-service:
    build:
      context: ./services/grades-service
      dockerfile: Dockerfile
    container_name: grades-service
    ports:
      - "${GRADES_SERVICE_PORT:-8001}:8001"
    environment:
      PORT_USER_SERVICE: ${GRADES_SERVICE_PORT:-8001}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped
  
  subjects-service:
    build:
      context: ./services/subjects-service
      dockerfile: Dockerfile
    container_name: subjects-service
    ports:
      - "${SUBJECTS_SERVICE_PORT:-8003}:8003"
    environment:
      PORT_SUBJECT_SERVICE: ${SUBJECTS_SERVICE_PORT:-8003}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  attendance-service:
    build:
      context: ./services/attendance-service
      dockerfile: Dockerfile
    container_name: attendance-service
    ports:
      - "${ATTENDANCE_SERVICE_PORT:-8004}:8004"
    environment:
      PORT_ATTENDANCE_SERVICE: ${ATTENDANCE_SERVICE_PORT:-8004}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  timetable-service:
    build:
      context: ./services/timetable-service
      dockerfile: Dockerfile
    container_name: timetable-service
    ports:
      - "${TIMETABLE_SERVICE_PORT:-8005}:8005"
    environment:
      PORT_TIMETABLE_SERVICE: ${TIMETABLE_SERVICE_PORT:-8005}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  messages-service:
    build:
      context: ./services/messages-service
      dockerfile: Dockerfile
    container_name: messages-service
    ports:
      - "${MESSAGES_SERVICE_PORT:-8006}:8006"
    environment:
      PORT_MESSAGES_SERVICE: ${MESSAGES_SERVICE_PORT:-8006}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  classes-service:
    build:
      context: ./services/classes-service
      dockerfile: Dockerfile
    container_name: classes-service
    ports:
      - "${CLASS_SERVICE_PORT:-8007}:8007"
    environment:
      PORT_MESSAGES_SERVICE: ${CLASS_SERVICE_PORT:-8007}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

networks:
  gradebook-net:

volumes:
  mongo_data:
  postgres_data:
  keycloak_data:
  keycloak_postgres_data:
