version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "${PORT_MONGO}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "${PORT_KEYCLOAK}:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    depends_on:
      - keycloak_postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  keycloak_postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KEYCLOAK_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - gradebook-net
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${PORT_RABBITMQ}:5672"
      - "${PORT2_RABBITMQ}:15672"
    networks:
      - gradebook-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${PORT_API_GATEWAY}:8081"
    environment:
      - PORT_API_GATEWAY=${PORT_API_GATEWAY}
      - PORT_USERS_SERVICE=${PORT_USERS_SERVICE}
      - PORT_GRADES_SERVICE=${PORT_GRADES_SERVICE}
      - PORT_SUBJECTS_SERVICE=${PORT_SUBJECTS_SERVICE}
      - PORT_ATTENDANCE_SERVICE=${PORT_ATTENDANCE_SERVICE}
      - PORT_TIMETABLE_SERVICE=${PORT_TIMETABLE_SERVICE}
      - PORT_MESSAGES_SERVICE=${PORT_MESSAGES_SERVICE}
      - PORT_CLASS_SERVICE=${PORT_CLASS_SERVICE}
      - PORT_REPORTS_CLIENT=${PORT_REPORTS_CLIENT}
    depends_on:
      - keycloak
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 5

  users-service:
    image: mkalejta/users-service:latest
    container_name: users-service
    ports:
      - "${PORT_USERS_SERVICE}:8001"
    environment:
      - PORT_USER_SERVICE=${PORT_USERS_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ADMIN_KEYCLOAK_CLIENT_ID=${ADMIN_KEYCLOAK_CLIENT_ID}
      - ADMIN_KEYCLOAK_CLIENT_SECRET=${ADMIN_KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  grades-service:
    image: mkalejta/grades-service:latest
    container_name: grades-service
    ports:
      - "${PORT_GRADES_SERVICE}:8002"
    environment:
      - PORT_GRADES_SERVICE=${PORT_GRADES_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  subjects-service:
    image: mkalejta/subjects-service:latest
    container_name: subjects-service
    ports:
      - "${PORT_SUBJECTS_SERVICE}:8003"
    environment:
      - PORT_SUBJECT_SERVICE=${PORT_SUBJECTS_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  attendance-service:
    image: mkalejta/attendance-service:latest
    container_name: attendance-service
    ports:
      - "${PORT_ATTENDANCE_SERVICE}:8004"
    environment:
      - PORT_ATTENDANCE_SERVICE=${PORT_ATTENDANCE_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  timetable-service:
    image: mkalejta/timetable-service:latest
    container_name: timetable-service
    ports:
      - "${PORT_TIMETABLE_SERVICE}:8005"
    environment:
      - PORT_TIMETABLE_SERVICE=${PORT_TIMETABLE_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  messages-service:
    image: mkalejta/messages-service:latest
    container_name: messages-service
    ports:
      - "${PORT_MESSAGES_SERVICE}:8006"
    environment:
      - PORT_MESSAGES_SERVICE=${PORT_MESSAGES_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  classes-service:
    image: mkalejta/classes-service:latest
    container_name: classes-service
    ports:
      - "${PORT_CLASS_SERVICE}:8007"
    environment:
      - PORT_CLASS_SERVICE=${PORT_CLASS_SERVICE}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
      - rabbitmq
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  web-client:
    build:
      context: ./clients/web-client
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - "${PORT_WEB_CLIENT}:${PORT_NGINX}"
    depends_on:
      - api-gateway
      - keycloak
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin-panel:
    build:
      context: ./clients/admin-panel
      dockerfile: Dockerfile
    container_name: admin-panel
    ports:
      - "${PORT_ADMIN_PANEL}:4000"
    environment:
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_PUBLIC_URL=${KEYCLOAK_PUBLIC_URL}
      - ADMIN_KEYCLOAK_REALM=${ADMIN_KEYCLOAK_REALM}
      - ADMIN_KEYCLOAK_CLIENT_ID=${ADMIN_KEYCLOAK_CLIENT_ID}
      - ADMIN_KEYCLOAK_CLIENT_SECRET=${ADMIN_KEYCLOAK_CLIENT_SECRET}
      - ADMIN_API_GATEWAY_URL=${ADMIN_API_GATEWAY_URL}
      - ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
    depends_on:
      - api-gateway
      - keycloak
      - redis
    networks:
      - gradebook-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  reports-client:
    build:
      context: ./clients/reports-client
      dockerfile: Dockerfile
    container_name: reports-client
    ports:
      - "${PORT_REPORTS_CLIENT}:4001"
    environment:
      - API_GATEWAY_URL=${REPORTS_API_GATEWAY_URL}
      - INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - REALM=${KEYCLOAK_REALM}
      - CLIENT_ID=${REPORTS_KEYCLOAK_CLIENT_ID}
      - CLIENT_SECRET=${REPORTS_KEYCLOAK_CLIENT_SECRET}
      - SHEET_ID=${SHEET_ID}
      - PORT=${PORT_REPORTS_CLIENT}
    depends_on:
      - api-gateway
      - keycloak
      - grades-service
      - classes-service
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - reports_data:/usr/src/app/reports

volumes:
  mongo_data:
  postgres_data:
  keycloak_data:
  keycloak_postgres_data:
  reports_data:

networks:
  gradebook-net:
    driver: bridge
