version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "${PORT_MONGO:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - gradebook-net
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "${PORT_POSTGRES:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    networks:
      - gradebook-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    ports:
      - "${PORT_KEYCLOAK:-8080}:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_postgres:5432/${KEYCLOAK_DB_NAME}
      - KC_DB_USERNAME=${KEYCLOAK_DB_USER}
      - KC_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - keycloak_postgres
    volumes:
     - keycloak_data:/opt/keycloak/data
     - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - gradebook-net
    restart: unless-stopped

  keycloak_postgres:
    image: postgres:16
    container_name: keycloak_postgres
    environment:
      - POSTGRES_DB=${KEYCLOAK_DB_NAME}
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - gradebook-net
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${PORT_API_GATEWAY:-8081}:8081"
    environment:
      - KEYCLOAK_PUBLIC_URL=${KEYCLOAK_PUBLIC_URL}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - PORT_API_GATEWAY=${PORT_API_GATEWAY:-8081}
    depends_on:
      - keycloak
    networks:
      - gradebook-net
    restart: unless-stopped

  users-service:
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "${PORT_USERS_SERVICE:-8001}:8001"
    environment:
      - PORT_USER_SERVICE=${PORT_USERS_SERVICE:-8001}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  grades-service:
    build:
      context: ./services/grades-service
      dockerfile: Dockerfile
    container_name: grades-service
    ports:
      - "${PORT_GRADES_SERVICE:-8002}:8002"
    environment:
      - PORT_GRADES_SERVICE=${PORT_GRADES_SERVICE:-8002}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped
  
  subjects-service:
    build:
      context: ./services/subjects-service
      dockerfile: Dockerfile
    container_name: subjects-service
    ports:
      - "${PORT_SUBJECTS_SERVICE:-8003}:8003"
    environment:
      - PORT_SUBJECT_SERVICE=${PORT_SUBJECTS_SERVICE:-8003}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  attendance-service:
    build:
      context: ./services/attendance-service
      dockerfile: Dockerfile
    container_name: attendance-service
    ports:
      - "${PORT_ATTENDANCE_SERVICE:-8004}:8004"
    environment:
      - PORT_ATTENDANCE_SERVICE=${PORT_ATTENDANCE_SERVICE:-8004}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  timetable-service:
    build:
      context: ./services/timetable-service
      dockerfile: Dockerfile
    container_name: timetable-service
    ports:
      - "${PORT_TIMETABLE_SERVICE:-8005}:8005"
    environment:
      - PORT_TIMETABLE_SERVICE=${PORT_TIMETABLE_SERVICE:-8005}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  messages-service:
    build:
      context: ./services/messages-service
      dockerfile: Dockerfile
    container_name: messages-service
    ports:
      - "${PORT_MESSAGES_SERVICE:-8006}:8006"
    environment:
      - PORT_MESSAGES_SERVICE=${PORT_MESSAGES_SERVICE:-8006}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped

  classes-service:
    build:
      context: ./services/classes-service
      dockerfile: Dockerfile
    container_name: classes-service
    ports:
      - "${PORT_CLASS_SERVICE:-8007}:8007"
    environment:
      - PORT_MESSAGES_SERVICE=${PORT_CLASS_SERVICE:-8007}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - NODE_PATH=${NODE_PATH}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./shared:/usr/src/app/shared:ro
    depends_on:
      - mongodb
      - postgres
    networks:
      - gradebook-net
    restart: unless-stopped
    
  web-client:
    build:
      context: ./clients/web-client
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - "${PORT_WEB_CLIENT:-5173}:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
      - VITE_PORT=5173
    depends_on:
      - api-gateway
      - keycloak
    networks:
      - gradebook-net
    restart: unless-stopped

networks:
  gradebook-net:

volumes:
  mongo_data:
  postgres_data:
  keycloak_data:
  keycloak_postgres_data:
