apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
        name: redis
        image: redis:7-alpine
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          failureThreshold: 5
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort: 6379
            protocol: TCP
      restartPolicy: Always
