apiVersion: v1
kind: Service
metadata:
  name: admin-panel
spec:
  type: LoadBalancer
  ports:
    - name: "admin"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: admin-panel
