apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: reports-client
  name: reports-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reports-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: reports-client
    spec:
      containers:
        - env:
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REPORTS_API_GATEWAY_URL
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REPORTS_KEYCLOAK_CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REPORTS_KEYCLOAK_CLIENT_SECRET
            - name: INTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_INTERNAL_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_REPORTS_CLIENT
            - name: REALM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_REALM
            - name: SHEET_ID
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SHEET_ID
          image: mkalejta/reports-client:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:4001/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: reports-client
          ports:
            - containerPort: 4001
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/reports
              name: reports-data
      restartPolicy: Always
      volumes:
        - name: reports-data
          persistentVolumeClaim:
            claimName: reports-data
