apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subjects-service-hpa
  namespace: dziennik
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subjects-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70