apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dziennik-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: /admin(/|$)(.*)
            backend:
              service:
                name: admin-panel
                port:
                  number: 4000
          - pathType: Prefix
            path: /api(/|$)(.*)
            backend:
              service:
                name: api-gateway
                port:
                  number: 8081
          - pathType: Prefix
            path: /keycloak(/|$)(.*)
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: web-client
                port:
                  number: 80